name: Create Release Zip
on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: MARS_SOM_OVERLAY/
          dest: MARS_SOM_OVERLAY.zip
