name: MARS_SOM_OVERLAY
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Releases
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore/' --exclude='.gitattributes' . ./release
    - name: Switch to Releases
      run: |
        cd release
        ls -la
    - name: Bump Version and push Tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: M1U5T0N3
        WITH_V: true
