name: Create Release Zip
on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: dist/MARS_SOM_OVERLAY
          recursive: false
          dest: MARS_SOM_OVERLAY.zip
